name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn builddocsts
      - run: yarn install --frozen-lockfile
        working-directory: ./vscode
      - run: yarn package
        working-directory: ./vscode
      - run: yarn distdocs
        env:
          GATSBY_GITHUB_REPOSITORY: ${{ github.repository }}
          GATSBY_GITHUB_REF: ${{ github.ref }}
          GATSBY_GITHUB_SHA: ${{ github.sha }}
          NODE_OPTIONS: --max-old-space-size=4096
      - name: github pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
